on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [^12.13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn install

      - name: Build, lint, test and package
        # Stuck on v1.0  because of https://github.com/GabrielBB/xvfb-action/issues/10
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: node make.js allDev

  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ^12.13
      - name: make.js - build, test, and package
        run: |
          yarn install
          node make.js all
