on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    env:
      VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: ^12.13

      - name: Yarn install
        run: yarn install

      - name: Build, lint, test and package
        # Stuck on v1.0  because of https://github.com/GabrielBB/xvfb-action/issues/10
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: node make.js all

      - name: Publish to VSCode extensions store
        run: node make.js publish -- ${{env.VSCE_TOKEN}}
